baseURL = "/"
languageCode = "en-us"
title = "Simon Lindgren"
theme = "orbit"

[params]

# Meta
    description = "My CV, created with Hugo, deployed with sws"
    author = "Simon Lindgren"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-5.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Simon Lindgren"
        tagline = "Backend Developer"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: simon.g.lindgren@gmail.com"
        title = "simon.g.lindgren@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+46722375051"
        title = "+4672 237 50 51"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/simon-lindgren-269102a4"
        title = "linkedin.com/in/simon-lindgren"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/czarsimon"
        title = "github.com/czarsimon"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "MSc in Strategy and Control"
        college = "University of Linköping"
        dates = "2011 - 2016"

        [[params.education.list]]
        degree = "BSc in Computer Engineering"
        college = "University of Linköping"
        dates = "2011 - 2013"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Swedish"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Fluent"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Coding :)"

	      [[params.interests.list]]
        interest = "Investing"

        [[params.interests.list]]
        interest = "Brewing beer"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "**Driven backend developer** with experience from industries such as med-tech, banking and games development. Used to work in a fast paced environments with short iteration loops and tight deadlines. Besides my roles as backend developer, I have had architectural responsibilities and been responsible for setting up test automation, continuous integration and deployment pipelines."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Backend Developer (consultant)"
        dates = "April 2018 - Present"
        company = "Doktor24"
        url = "https://doktor24.se"
        details = "**Part of the team designing and developing the backend plattform for Dotkor24** a med-tech startup in Stockholm with a goal of making primary care digitally accessible for patients and more efficent for doctors. My responsibilities include developing and designing backend services in Java and Python as well as DevOps task such as deployment, cicd and monitoring setup for the plattform with tools such as Kubernetes, Docker and Jenkins."

        [[params.jobs.list]]
        position = "DevOps Engineering Consultant"
        dates = "March 2018 - April 2018"
        company = "Mojang AB"
        details = "**Designed and developed a system for tracking open source dependencies** in all the teams source code repos as well as automating the verification that libraries where acceptable for use. The system was developed in Python and run on AWS using technologies such as AWS Lambda, Simple Queue Service and Aurora."

        [[params.jobs.list]]
        position = "Integration Architect"
        dates = "Q2 2017 - Q2 2018"
        company = "Accenture AB - Banking client, Stockholm"
        details = "**As part of a project, implementing a large scale batch processing engine** for banking client, I held the role as Integration Architect. Responsibilities included designing interfaces and integration patterns with external and internal services, as well as setting up the application from an infrastructructure perspective for high availability and disaster recovery. Further I was responsible for setting up continuous integration and deployment pipelines."

        [[params.jobs.list]]
        position = "Backend Developer"
        dates = "Q3 2016 - Q2 2018"
        company = "Accenture AB - Banking client, Stockholm"
        details = "**Responsibility for developing backend http APIs and Apache Kafka consumers** as part of a larger project to build a batch processing engine. Both were implemented in Java 8 using the spring framework and kafka consumer APIs. Challenges included designing the kafka consumers for extreme peaks of message volumes during intermittent reporting periods, which the previous message system consumers were unable to handle. The work resulted in an order of magnitude performance improvement in message handling."

        [[params.jobs.list]]
        position = "Test Automation Lead"
        dates = "Q3 2016 - Q2 2017"
        company = "Accenture AB - Banking client, Stockholm"
        details = "**Responsible for developing a test automation tool** for running system and regression testing on a highly stateful batch processing application implemented in and Oracle database. The test tool was implemented in Java using reflection and allowed individual testers and developers to write declarative test cases in JSON configuration files, simply declaring expected prior state, test steps and expected result. The created written test cases were then automatically picked up, ran and reported by the continuous integration pipeline. The tool and automation approach was successfully rolled out in the project and repeatedly demonstrated to other projects within the client as a model for other test automation efforts."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"

        [[params.projects.list]]
        title = "mimir"
        url = "https://github.com/CzarSimon/mimir"
        tagline = "News application that gathers, clusters and ranks stock news based on real time streams from twitter and scraping linked news articles. The application presents a list of the most relevant news based on each individual users stock portfolio. The backend uses a microservices architecture with services written in Go, Python and Java, fully containerized and deployed with Kubernetes on AWS. The frontend is written in Javascript with React and React Native"

        [[params.projects.list]]
        title = "sws"
        url = "https://github.com/czarsimon/sws"
        tagline = "Tool for running multiple outward facing services in containers on a single host and proxy to them based on domain. Supports declaritve description of services, updating a service without interupting others. Used to serve this page :)"

        [[params.projects.list]]
        title = "dockmon"
        url = "https://github.com/czarsimon/dockmon"
        tagline = "Liveness probing and and service restarting agent for docker containers on a single node. Allows users to specify any number of containers for which to conduct liveness probes, the frequency of health checks and optionally if a service should be restarted when it becomes unhealthy. Inspired by the Kubernetes liveness probing API with the goal of making the same service stability availibe of smaller hobby project. Used to monitor a number of my hobby projects and this site :)"

        [[params.projects.list]]
        title = "service-controller"
        url = "https://github.com/czarsimon/service-controller"
        tagline = "System and command line utility for bringing up, managing a Docker swarm cluster, and declaratively specifying containerized services to be deployed on the cluster. The system works by installing a worker service on all worker and master nodes in the cluster, that join a given Docker swarm, sets up necessary networking and storage volumes and coordinates container versions across the cluster."

        [[params.projects.list]]
        title = "monkey"
        url = "https://github.com/czarsimon/monkey"
        tagline = "Interpreter for a dynamically typed programming language with first class functions. Implemented and fully tested in golang."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Python"
        level = "85%"

        [[params.skills.list]]
        skill = "Go"
        level = "80%"

	      [[params.skills.list]]
        skill = "Java"
        level = "80%"

        [[params.skills.list]]
        skill = "Javascript"
        level = "75%"

        [[params.skills.list]]
        skill = "React"
        level = "70%"

	      [[params.skills.list]]
        skill = "Apache Kafka"
        level = "70%"

	      [[params.skills.list]]
        skill = "Docker"
        level = "90%"

	      [[params.skills.list]]
        skill = "Kubernetes"
        level = "75%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
